version: "3.8"

services:
  quizbot:
    build: .
    environment:
      TOKEN: ${TOKEN}
      USUARIOS_GESTION_TESTS: ${USUARIOS_GESTION_TESTS:-}
    restart: unless-stopped
    volumes:
      - /mnt/data/bot:/app/bd
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
